//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotebookMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Note()
        {
            this.NoteBooks = new HashSet<NoteBook>();
        }

        /// <summary>
        /// Unique Id of the Note
        /// </summary>
        public long NoteId { get; set; }
        /// <summary>
        /// Id of the assoicated Notebook
        /// </summary>
        public long NoteBookId { get; set; }
        /// <summary>
        /// Subject of the Note
        /// </summary>
        public string Subject { get; set; }
        /// <summary>
        /// Note's Text
        /// </summary>
        public string NoteText { get; set; }
        /// <summary>
        /// Date Note was Created
        /// </summary>
        public System.DateTime CreateDate { get; set; }
        /// <summary>
        /// TS of when the note was last updated
        /// </summary>
        public System.DateTime UpdateDate { get; set; }

        public virtual NoteBook NoteBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteBook> NoteBooks { get; set; }
    }
}
